import type {UberId} from "../types/UberStates"

const teleporterValueConverter = (value: number) => value & 0b1
const thresholdOf = (threshold: number) => (value: number) => value >= threshold ? 1 : 0

const trackedUberStates = [
  {uberId: {group: 0, state: 0}, trackingId: "treeBash"},
  {uberId: {group: 0, state: 5}, trackingId: "treeDoubleJump"},
  {uberId: {group: 0, state: 8}, trackingId: "treeLaunch"},
  {uberId: {group: 0, state: 51}, trackingId: "treeLightBurst"},
  {uberId: {group: 0, state: 57}, trackingId: "treeGrapple"},
  {uberId: {group: 0, state: 62}, trackingId: "treeFlash"},
  {uberId: {group: 0, state: 77}, trackingId: "treeRegenerate"},
  {uberId: {group: 0, state: 97}, trackingId: "treeBow"},
  {uberId: {group: 0, state: 100}, trackingId: "treeSword"},
  {uberId: {group: 0, state: 101}, trackingId: "treeBurrow"},
  {uberId: {group: 0, state: 102}, trackingId: "treeDash"},
  {uberId: {group: 0, state: 104}, trackingId: "treeWaterDash"},
  {uberId: {group: 0, state: 120}, trackingId: "treeAncestralLightGlades"},
  {uberId: {group: 0, state: 121}, trackingId: "treeAncestralLightMarsh"},

  {uberId: {group: 24922, state: 42531}, trackingId: "tpMidnightBurrows", valueConverter: teleporterValueConverter},
  {uberId: {group: 21786, state: 10185}, trackingId: "tpInkwaterMarsh", valueConverter: teleporterValueConverter},
  {uberId: {group: 11666, state: 61594}, trackingId: "tpHowlsDen", valueConverter: teleporterValueConverter},
  {uberId: {group: 945, state: 58183}, trackingId: "tpLumaPoolsEast", valueConverter: teleporterValueConverter},
  {uberId: {group: 945, state: 1370}, trackingId: "tpLumaPoolsWest", valueConverter: teleporterValueConverter},
  {uberId: {group: 53632, state: 18181}, trackingId: "tpWellspring", valueConverter: teleporterValueConverter},
  {uberId: {group: 28895, state: 54235}, trackingId: "tpBaursReach", valueConverter: teleporterValueConverter},
  {uberId: {group: 937, state: 26601}, trackingId: "tpKwoloksHollow", valueConverter: teleporterValueConverter},
  {uberId: {group: 18793, state: 38871}, trackingId: "tpMouldwoodDepths", valueConverter: teleporterValueConverter},
  {uberId: {group: 16155, state: 41465}, trackingId: "tpWillowInner", valueConverter: teleporterValueConverter},
  {uberId: {group: 16155, state: 50867}, trackingId: "tpWillowOuter", valueConverter: teleporterValueConverter},
  {uberId: {group: 58674, state: 7071}, trackingId: "tpSilentWoodsWest", valueConverter: teleporterValueConverter},
  {uberId: {group: 58674, state: 1965}, trackingId: "tpSilentWoodsWast", valueConverter: teleporterValueConverter},
  {
    uberId: {group: 58674, state: 10029},
    trackingId: "tpWindsweptWastesWest",
    valueConverter: teleporterValueConverter,
  },
  {
    uberId: {group: 20120, state: 49994},
    trackingId: "tpWindsweptWastesEast",
    valueConverter: teleporterValueConverter,
  },
  {
    uberId: {group: 20120, state: 41398},
    trackingId: "tpWindtornRuinsOuter",
    valueConverter: teleporterValueConverter,
  },
  {
    uberId: {group: 10289, state: 4928},
    trackingId: "tpWindtornRuinsInner",
    valueConverter: teleporterValueConverter,
  },
  {uberId: {group: 42178, state: 42096}, trackingId: "tpWellspringGlades", valueConverter: teleporterValueConverter},

  {uberId: {group: 24, state: 0}, trackingId: "skillBash"},
  {uberId: {group: 24, state: 3}, trackingId: "skillWallJump"},
  {uberId: {group: 24, state: 5}, trackingId: "skillDoubleJump"},
  {uberId: {group: 24, state: 8}, trackingId: "skillLaunch"},
  {uberId: {group: 24, state: 14}, trackingId: "skillGlide"},
  {uberId: {group: 24, state: 23}, trackingId: "skillWaterBreath"},
  {uberId: {group: 24, state: 51}, trackingId: "skillLightBurst"},
  {uberId: {group: 24, state: 57}, trackingId: "skillGrapple"},
  {uberId: {group: 24, state: 62}, trackingId: "skillFlash"},
  {uberId: {group: 24, state: 74}, trackingId: "skillSpike"},
  {uberId: {group: 24, state: 77}, trackingId: "skillRegenerate"},
  {uberId: {group: 24, state: 97}, trackingId: "skillBow"},
  {uberId: {group: 24, state: 98}, trackingId: "skillHammer"},
  {uberId: {group: 24, state: 99}, trackingId: "skillTorch"},
  {uberId: {group: 24, state: 100}, trackingId: "skillSword"},
  {uberId: {group: 24, state: 101}, trackingId: "skillBurrow"},
  {uberId: {group: 24, state: 102}, trackingId: "skillDash"},
  {uberId: {group: 24, state: 104}, trackingId: "skillWaterDash"},
  {uberId: {group: 24, state: 106}, trackingId: "skillShuriken"},
  {uberId: {group: 24, state: 115}, trackingId: "skillBlaze"},
  {uberId: {group: 24, state: 116}, trackingId: "skillSentry"},
  {uberId: {group: 24, state: 118}, trackingId: "skillFlap"},
  {uberId: {group: 24, state: 120}, trackingId: "skillAncestralLightGlades"},
  {uberId: {group: 24, state: 121}, trackingId: "skillAncestralLightMarsh"},
  {uberId: {group: 6, state: 2000}, trackingId: "skillCleanWater"},

  {uberId: {group: 4, state: 70}, trackingId: "meltingBow"},
  {uberId: {group: 4, state: 71}, trackingId: "meltingBlaze"},
  {uberId: {group: 4, state: 72}, trackingId: "meltingSword"},
  {uberId: {group: 4, state: 73}, trackingId: "meltingHammer"},
  {uberId: {group: 4, state: 74}, trackingId: "meltingSpike"},
  {uberId: {group: 4, state: 75}, trackingId: "meltingShuriken"},

  {uberId: {group: 5, state: 0}, trackingId: "resourceSpiritLight"},
  {uberId: {group: 5, state: 1}, trackingId: "resourceGorlekOre"},
  {uberId: {group: 14, state: 5}, trackingId: "resourceGorlekOreCollected"},
  {uberId: {group: 5, state: 2}, trackingId: "resourceKeystones"},

  {uberId: {group: 23, state: 1}, trackingId: "launchFragmentsCount"},
  {uberId: {group: 23, state: 2}, trackingId: "launchFragmentsRequired"},
  {uberId: {group: 23, state: 100}, trackingId: "treesCount"},
  {uberId: {group: 23, state: 101}, trackingId: "treesRequired"},
  {uberId: {group: 23, state: 102}, trackingId: "wispsCount"},
  {uberId: {group: 23, state: 103}, trackingId: "wispsRequired"},
  {uberId: {group: 23, state: 104}, trackingId: "questsCount"},
  {uberId: {group: 23, state: 105}, trackingId: "questsRequired"},
  {uberId: {group: 23, state: 106}, trackingId: "relicsCount"},
  {uberId: {group: 23, state: 107}, trackingId: "relicsRequired"},
  {uberId: {group: 24, state: 200}, trackingId: "showVisitedEntranceCount"},
  {uberId: {group: 23, state: 500}, trackingId: "relicCurrentAreaUncollected"},

  {uberId: {group: 16155, state: 42976}, trackingId: "heartWindSpinners"},
  {uberId: {group: 16155, state: 54940}, trackingId: "heartSpinningLasers"},
  {uberId: {group: 16155, state: 24290}, trackingId: "heartUpperHeart"},
  {uberId: {group: 16155, state: 3588}, trackingId: "heartBurrowHeart"},
  {uberId: {group: 16155, state: 12971}, trackingId: "heartWillowLaser", valueConverter: thresholdOf(4)},
  {uberId: {group: 16155, state: 65277}, trackingId: "heartRedirectPuzzle"},
  {uberId: {group: 16155, state: 41488}, trackingId: "heartBoulderEscape"},
  {uberId: {group: 16155, state: 60752}, trackingId: "heartLowerLeft"},

  {uberId: {group: 34543, state: 11226}, trackingId: "gameFinished"},

  {uberId: {group: 14019, state: 44578}, trackingId: "questRebuildGlades"},

  {uberId: {group: 42178, state: 16825}, trackingId: "builderProjectSpiritWell"},
  {uberId: {group: 42178, state: 51230}, trackingId: "builderProjectHouses"},
  {uberId: {group: 42178, state: 18751}, trackingId: "builderProjectRemoveThorns"},
  {uberId: {group: 42178, state: 23607}, trackingId: "builderProjectHousesB"},
  {uberId: {group: 42178, state: 40448}, trackingId: "builderProjectHousesC"},
  {uberId: {group: 42178, state: 16586}, trackingId: "builderProjectOpenCave"},
  {uberId: {group: 42178, state: 15068}, trackingId: "builderProjectBeautify"},

  {uberId: {group: 28, state: 1}, trackingId: "lupoShopOutside"},
  {uberId: {group: 28, state: 2}, trackingId: "lupoShopInside"},
  {uberId: {group: 28, state: 3}, trackingId: "lastHutOutside"},
  {uberId: {group: 28, state: 4}, trackingId: "lastHutInside"},
  {uberId: {group: 28, state: 5}, trackingId: "hutAboveMotayOutside"},
  {uberId: {group: 28, state: 6}, trackingId: "hutAboveMotayInside"},
  {uberId: {group: 28, state: 7}, trackingId: "treeHutOutside"},
  {uberId: {group: 28, state: 8}, trackingId: "treeHutInside"},
  {uberId: {group: 28, state: 9}, trackingId: "mokiFatherHutOutside"},
  {uberId: {group: 28, state: 10}, trackingId: "mokiFatherHutInside"},
  {uberId: {group: 28, state: 11}, trackingId: "storageHutOutside"},
  {uberId: {group: 28, state: 12}, trackingId: "storageHutInside"},
  {uberId: {group: 28, state: 13}, trackingId: "caveOutside"},
  {uberId: {group: 28, state: 14}, trackingId: "caveInside"},
  {uberId: {group: 28, state: 15}, trackingId: "wellspring1stFloorBottomOutside"},
  {uberId: {group: 28, state: 16}, trackingId: "wellspring1stFloorBottomInside"},
  {uberId: {group: 28, state: 17}, trackingId: "wellspring1stFloorTopOutside"},
  {uberId: {group: 28, state: 18}, trackingId: "wellspring1stFloorTopInside"},
  {uberId: {group: 28, state: 19}, trackingId: "wellspring2ndFloorOutside"},
  {uberId: {group: 28, state: 20}, trackingId: "wellspring2ndFloorInside"},
  {uberId: {group: 28, state: 21}, trackingId: "wellspring3rdFloorOutside"},
  {uberId: {group: 28, state: 22}, trackingId: "wellspring3rdFloorInside"},
  {uberId: {group: 28, state: 23}, trackingId: "reachSeedOutside"},
  {uberId: {group: 28, state: 24}, trackingId: "reachSeedInside"},
  {uberId: {group: 28, state: 25}, trackingId: "teddyHutOutside"},
  {uberId: {group: 28, state: 26}, trackingId: "teddyHutInside"},
  {uberId: {group: 28, state: 27}, trackingId: "ruinsOutside"},
  {uberId: {group: 28, state: 28}, trackingId: "ruinsInside"},
  {uberId: {group: 28, state: 29}, trackingId: "willowBottomOutside"},
  {uberId: {group: 28, state: 30}, trackingId: "willowBottomInside"},
  {uberId: {group: 28, state: 31}, trackingId: "willowTopInside"},
  {uberId: {group: 28, state: 32}, trackingId: "willowTopOutside"},

  // Maybe for later...
  {uberId: {group: 945, state: 49747}, trackingId: "wispPools"},
  {uberId: {group: 28895, state: 25522}, trackingId: "wispReach"},
  {uberId: {group: 18793, state: 63291}, trackingId: "wispDepths"},
  {uberId: {group: 46462, state: 59806}, trackingId: "wispHollow"},
  {uberId: {group: 10289, state: 22102}, trackingId: "wispRuins"},
] as const

export type TrackedUberState = {
  uberId: UberId,
  trackingId: typeof trackedUberStates[number]["trackingId"],
  valueConverter?: (value: number) => number
}

export const TRACKED_UBER_STATES: readonly TrackedUberState[] = trackedUberStates
