/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a seed
         * @description Response will be in CBOR format
         *
         *     ```cddl
         *     universe = {
         *         worlds: [ +bstr ],
         *         ? json_spoiler: tstr,
         *         ? text_spoiler: tstr,
         *         logs: [ *record ],
         *     }
         *
         *     record = {
         *         level: level,
         *         message: tstr
         *     }
         *
         *     level = "ERROR" / "WARN" / "INFO" / "DEBUG" / "TRACE"
         *     ```
         */
        post: {
            parameters: {
                query?: {
                    json_spoiler?: boolean | null;
                    text_spoiler?: boolean | null;
                    max_log_level?: null | components["schemas"]["LogLevelFilter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UniverseSettings"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": number[];
                    };
                };
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logic/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the logic graph */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Graph"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logic/map-icons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of logically relevant map icons */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapIcons"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logic/reach-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a list of reachable nodes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReachCheckBody"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReachCheck"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logic/relevant-uber-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of logically relevant UberStates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RelevantUberStates"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logic/spawn-anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of spawnable anchor identifiers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpawnAnchors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plando/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile a plandomizer
         * @description Response will be in CBOR format
         *
         *     ```cddl
         *     output = {
         *         seed: bstr,
         *         logs: [ *record ],
         *     }
         *
         *     record = {
         *         level: level,
         *         message: tstr
         *     }
         *
         *     level = "ERROR" / "WARN" / "INFO" / "DEBUG" / "TRACE"
         *     ```
         */
        post: {
            parameters: {
                query?: {
                    debug?: boolean | null;
                    max_log_level?: null | components["schemas"]["LogLevelFilter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HashMap_String_Source"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": number[];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/universe/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a universe preset to universe settings */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UniversePresetApplyBody"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniversePresetApplyBody"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/universe/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of available universe presets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HashMap_String_UniversePresetInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/world/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply world presets to world settings.
         *     If no settings are given, presets are applied on top of the default world settings.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorldPresetApplyBody"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorldSettings"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/world/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of available world presets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HashMap_String_WorldPresetInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/difficulties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the sorted list of difficulties in ascending order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DifficultyInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/tricks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of tricks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrickInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/universe/inline-snippets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inline all snippets originating from the data directory */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UniverseSettings"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniverseSettings"];
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/universe/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start new universe settings */
        get: {
            parameters: {
                query: {
                    seed: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniverseSettings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/world/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the default world settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorldSettings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/world/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get random world settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorldSettings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snippets/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get detailed info about available snippets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HashMap_String_SnippetInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spoilers/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render a JSON spoiler into plaintext form */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeedSpoiler"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Text alignment in messages
         * @enum {integer}
         */
        Alignment: 0 | 1 | 2 | 3;
        Anchor: {
            can_spawn: boolean;
            connections: components["schemas"]["Connection"][];
            entrance?: null | components["schemas"]["Entrance"];
            identifier: string;
            position?: null | components["schemas"]["Position"];
            refills: components["schemas"]["Refill"][];
            teleport_restriction: components["schemas"]["Requirement"];
        };
        /** @description Origin of an asset */
        AssetOrigin: {
            /** @enum {string} */
            kind: "ExecutableDir";
        } | {
            /** @enum {string} */
            kind: "UserDataDir";
            path: string;
        };
        /** @enum {string} */
        ClientEvent: "Spawn" | "Reload" | "Respawn" | "Binding1" | "Binding2" | "Binding3" | "Binding4" | "Binding5" | "ProgressMessage" | "Tick" | "InkwaterTrialTextRequest" | "HollowTrialTextRequest" | "WellspringTrialTextRequest" | "WoodsTrialTextRequest" | "ReachTrialTextRequest" | "DepthsTrialTextRequest" | "LumaTrialTextRequest" | "WastesTrialTextRequest";
        /** @description Command which returns [`bool`] */
        CommandBoolean: {
            /** @description Return `value` */
            Constant: {
                value: boolean;
            };
        } | {
            /** @description Return the `index`th boolean function argument */
            FunctionArgument: {
                index: number;
            };
        } | {
            /** @description Execute `commands`, then use `last` for the return value */
            Multi: {
                commands: components["schemas"]["CommandVoid"][];
                last: components["schemas"]["CommandBoolean"];
            };
        } | {
            /** @description Return the result of `operation` */
            CompareBoolean: {
                operation: components["schemas"]["Operation_CommandBoolean_EqualityComparator"];
            };
        } | {
            /** @description Return the result of `operation` */
            CompareInteger: {
                operation: components["schemas"]["Operation_CommandInteger_Comparator"];
            };
        } | {
            /** @description Return the result of `operation` */
            CompareFloat: {
                operation: components["schemas"]["Operation_CommandFloat_Comparator"];
            };
        } | {
            /** @description Return the result of `operation` */
            CompareString: {
                operation: components["schemas"]["Operation_CommandString_EqualityComparator"];
            };
        } | {
            /** @description Return the result of `operation` */
            CompareZone: {
                operation: components["schemas"]["Operation_CommandZone_EqualityComparator"];
            };
        } | {
            /** @description Return the result of `operation` */
            LogicOperation: {
                operation: components["schemas"]["Operation_CommandBoolean_LogicOperator"];
            };
        } | {
            /** @description Return the value stored in `uber_identifier` */
            FetchBoolean: {
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Get the value stored under `id` */
            GetBoolean: {
                id: number;
            };
        } | {
            /** @description Check if Ori is in box defined by the circle center (x, y) and radius r */
            IsInCircle: {
                r: components["schemas"]["CommandFloat"];
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Check if Ori is in a position trigger with the given id */
            IsInPositionTrigger: {
                id: number;
            };
        } | {
            /** @description Check if Ori is in box defined by the rectangle (x1, y1) and (x2, y2) */
            IsInRectangle: {
                x1: components["schemas"]["CommandFloat"];
                x2: components["schemas"]["CommandFloat"];
                y1: components["schemas"]["CommandFloat"];
                y2: components["schemas"]["CommandFloat"];
            };
        };
        /** @description Command which returns [`f32`] */
        CommandFloat: {
            /** @description Return `value` */
            Constant: {
                /** Format: float */
                value: number;
            };
        } | {
            /** @description Return the `index`th boolean function argument */
            FunctionArgument: {
                index: number;
            };
        } | {
            /** @description Execute `commands`, then use `last` for the return value */
            Multi: {
                commands: components["schemas"]["CommandVoid"][];
                last: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Return the result of `operation` */
            Arithmetic: {
                operation: components["schemas"]["Operation_CommandFloat_ArithmeticOperator"];
            };
        } | {
            /** @description Return the value stored in `uber_identifier` */
            FetchFloat: {
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Get the value stored under `id` */
            GetFloat: {
                id: number;
            };
        } | {
            /** @description Convert `integer` to `f32` */
            FromInteger: {
                integer: components["schemas"]["CommandInteger"];
            };
        };
        /** @description Command which returns [`i32`] */
        CommandInteger: {
            /** @description Return `value` */
            Constant: {
                /** Format: int32 */
                value: number;
            };
        } | {
            /** @description Return the `index`th boolean function argument */
            FunctionArgument: {
                index: number;
            };
        } | {
            /** @description Execute `commands`, then use `last` for the return value */
            Multi: {
                commands: components["schemas"]["CommandVoid"][];
                last: components["schemas"]["CommandInteger"];
            };
        } | {
            /** @description Return the result of `operation` */
            Arithmetic: {
                operation: components["schemas"]["Operation_CommandInteger_ArithmeticOperator"];
            };
        } | {
            /** @description Return the value stored in `uber_identifier` */
            FetchInteger: {
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Get the value stored under `id` */
            GetInteger: {
                id: number;
            };
        } | {
            /** @description Convert `float` to `f32` */
            FromFloat: {
                float: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Get the length of `string` */
            StringLength: {
                string: components["schemas"]["CommandString"];
            };
        };
        /** @description Command which returns [`StringOrPlaceholder`] */
        CommandString: {
            /** @description Return `value` */
            Constant: {
                value: components["schemas"]["StringOrPlaceholder"];
            };
        } | {
            /** @description Return the `index`th boolean function argument */
            FunctionArgument: {
                index: number;
            };
        } | {
            /** @description Execute `commands`, then use `last` for the return value */
            Multi: {
                commands: components["schemas"]["CommandVoid"][];
                last: components["schemas"]["CommandString"];
            };
        } | {
            /** @description Return a String consisting of `left`, then `right` */
            Concatenate: {
                operation: components["schemas"]["Operation_CommandString_Concatenator"];
            };
        } | {
            /** @description Get the value stored under `id` */
            GetString: {
                id: number;
            };
        } | {
            /** @description Return the name of world number `index` */
            WorldName: {
                index: number;
            };
        } | {
            /** @description Convert `boolean` to `String` */
            FromBoolean: {
                boolean: components["schemas"]["CommandBoolean"];
            };
        } | {
            /** @description Convert `integer` to `String` */
            FromInteger: {
                integer: components["schemas"]["CommandInteger"];
            };
        } | {
            /** @description Convert `float` to `String` */
            FromFloat: {
                float: components["schemas"]["CommandFloat"];
            };
        };
        /** @description Command which returns nothing */
        CommandVoid: {
            /** @description Execute `commands` */
            Multi: {
                commands: components["schemas"]["CommandVoid"][];
            };
        } | {
            /** @description Call the function at `index` with the given arguments */
            CallFunction: {
                booleans: components["schemas"]["CommandBoolean"][];
                floats: components["schemas"]["CommandFloat"][];
                index: number;
                integers: components["schemas"]["CommandInteger"][];
                strings: components["schemas"]["CommandString"][];
            };
        } | {
            /** @description Only perform `command` if `condition` evaluates to true */
            If: {
                command: components["schemas"]["CommandVoid"];
                condition: components["schemas"]["CommandBoolean"];
            };
        } | {
            /** @description Until the next reload, on every tick where `toggle` is `true` increment `timer` by the delta time in seconds */
            DefineTimer: {
                timer: components["schemas"]["UberIdentifier"];
                toggle: components["schemas"]["UberIdentifier"];
            };
        } | {
            /**
             * @description Add `message` to the queue with `timeout` or a default timeout.
             *     If `priority` is true, it should be a priority message.
             *     If `id` is specified, it can later be used to update the message
             */
            QueuedMessage: {
                id?: number | null;
                message: components["schemas"]["CommandString"];
                priority: boolean;
                timeout?: null | components["schemas"]["CommandFloat"];
            };
        } | {
            /**
             * @description Sets the pickup position for queued messages until the end of the
             *     current command scope.
             *     The pickup position is used for animating item messages
             *     from their pickup positions.
             */
            QueuedMessageScopedPickupPosition: {
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Show `message` immediately independent of the queue */
            FreeMessage: {
                id: number;
                message: components["schemas"]["CommandString"];
            };
        } | {
            /** @description Register a free message with no text or visibility */
            FreeMessageUninitialized: {
                id: number;
            };
        } | {
            /** @description DESTROY message `id` */
            MessageDestroy: {
                id: number;
            };
        } | {
            /** @description Update the `message` of message `id` */
            MessageText: {
                id: number;
                message: components["schemas"]["CommandString"];
            };
        } | {
            /** @description Update the `timeout` of message `id` */
            MessageTimeout: {
                id: number;
                timeout: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Update whether message `id` has a `background` */
            MessageBackground: {
                background: components["schemas"]["CommandBoolean"];
                id: number;
            };
        } | {
            /** @description Update the `position` of free message `id` */
            FreeMessagePosition: {
                id: number;
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Update the `alignment` of free message `id` */
            FreeMessageAlignment: {
                alignment: components["schemas"]["Alignment"];
                id: number;
            };
        } | {
            /** @description Set the `horizontal_anchor` of free message `id` */
            FreeMessageHorizontalAnchor: {
                horizontal_anchor: components["schemas"]["HorizontalAnchor"];
                id: number;
            };
        } | {
            /** @description Set the `vertical_anchor` of free message `id` */
            FreeMessageVerticalAnchor: {
                id: number;
                vertical_anchor: components["schemas"]["VerticalAnchor"];
            };
        } | {
            FreeMessageBoxWidth: {
                id: number;
                width: components["schemas"]["CommandFloat"];
            };
        } | {
            FreeMessageCoordinateSystem: {
                coordinate_system: components["schemas"]["CoordinateSystem"];
                id: number;
            };
        } | {
            FreeMessageShow: {
                fade: components["schemas"]["CommandBoolean"];
                id: number;
                sound: components["schemas"]["CommandBoolean"];
            };
        } | {
            FreeMessageHide: {
                fade: components["schemas"]["CommandBoolean"];
                id: number;
            };
        } | {
            /** @description Store `value` in `uber_identifier` and check if any events are triggered */
            StoreBoolean: {
                trigger_events: boolean;
                uber_identifier: components["schemas"]["UberIdentifier"];
                value: components["schemas"]["CommandBoolean"];
            };
        } | {
            /** @description Store `value` in `uber_identifier` and check if any events are triggered */
            StoreInteger: {
                trigger_events: boolean;
                uber_identifier: components["schemas"]["UberIdentifier"];
                value: components["schemas"]["CommandInteger"];
            };
        } | {
            /** @description Store `value` in `uber_identifier` and check if any events are triggered */
            StoreFloat: {
                trigger_events: boolean;
                uber_identifier: components["schemas"]["UberIdentifier"];
                value: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Temporarily store `value` under `id`. The value should live at least until the next tick */
            SetBoolean: {
                id: number;
                value: components["schemas"]["CommandBoolean"];
            };
        } | {
            /** @description Temporarily store `value` under `id`. The value should live at least until the next tick */
            SetInteger: {
                id: number;
                value: components["schemas"]["CommandInteger"];
            };
        } | {
            /** @description Temporarily store `value` under `id`. The value should live at least until the next tick */
            SetFloat: {
                id: number;
                value: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Temporarily store `value` under `id`. The value should live at least until the next tick */
            SetString: {
                id: number;
                value: components["schemas"]["CommandString"];
            };
        } | {
            /** @description Create a new circular position defined by center (`x`, `y`) and radius `r` */
            PositionTriggerCircle: {
                id: number;
                r: components["schemas"]["CommandFloat"];
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Create a new rectangular position trigger defined by (`x1`, `y1`) and (`x2`, `y2`) */
            PositionTriggerRectangle: {
                id: number;
                x1: components["schemas"]["CommandFloat"];
                x2: components["schemas"]["CommandFloat"];
                y1: components["schemas"]["CommandFloat"];
                y2: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description DESTROY box `id` */
            PositionTriggerDestroy: {
                id: number;
            };
        } | {
            /** @description Register `action` to trigger when Ori enters box `id` */
            PositionTriggerEnterCallback: {
                action: number;
                id: number;
            };
        } | {
            /** @description Register `action` to trigger when Ori leaves box `id` */
            PositionTriggerLeaveCallback: {
                action: number;
                id: number;
            };
        } | {
            /** @description Save the game */
            Save: {
                to_disk: boolean;
            };
        } | {
            /** @description Save the game at `position` */
            SaveAt: {
                to_disk: boolean;
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Warp the player to (`x`, `y`) */
            Warp: {
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Instantly Warp the player to (`x`, `y`) */
            InstantWarp: {
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Equip `equipment` into `slot` */
            Equip: {
                equipment: components["schemas"]["Equipment"];
                slot: components["schemas"]["EquipSlot"];
            };
        } | {
            /** @description Unequip `equipment` from any slot it may be equipped in */
            Unequip: {
                equipment: components["schemas"]["Equipment"];
            };
        } | {
            /** @description Act as though the client would have sent `client_event` */
            TriggerClientEvent: {
                client_event: components["schemas"]["ClientEvent"];
            };
        } | {
            /** @description Act as though the user would have pressed `bind` */
            TriggerKeybind: {
                bind: string;
            };
        } | {
            /** @description Start syncing `uber_identifier` in co-op */
            EnableServerSync: {
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Stop syncing `uber_identifier` in co-op */
            DisableServerSync: {
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Create a spoiler map icon with `id` and `icon` at (`x`, `y`) with the label set to `label` */
            CreateSpoilerMapIcon: {
                icon: components["schemas"]["MapIcon"];
                id: number;
                label: components["schemas"]["CommandString"];
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Marks spoiler map icon with id `id` as collected */
            MarkSpoilerMapIconCollected: {
                id: number;
            };
        } | {
            /** @description Create a stats entry with `icon` with the label set to `label` */
            CreateStatsEntry: {
                icon: components["schemas"]["MapIcon"];
                label: components["schemas"]["CommandString"];
            };
        } | {
            /** @description Create a spirit well icon that you can warp to on the map at (`x`, `y`) */
            CreateWarpIcon: {
                id: number;
                x: components["schemas"]["CommandFloat"];
                y: components["schemas"]["CommandFloat"];
            };
        } | {
            /** @description Set the map label of an existing spirit well icon `id` to `label` */
            SetWarpIconLabel: {
                id: number;
                label: components["schemas"]["CommandString"];
            };
        } | {
            /** @description DESTROY the spirit well icon `id` */
            DestroyWarpIcon: {
                id: number;
            };
        } | {
            /** @description Set the price of the shop item at `uber_identifier` to `price` */
            SetShopItemPrice: {
                price: components["schemas"]["CommandInteger"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Set the display name of the shop item at `uber_identifier` to `name` */
            SetShopItemName: {
                name: components["schemas"]["CommandString"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Set the description of the shop item at `uber_identifier` to `description` */
            SetShopItemDescription: {
                description: components["schemas"]["CommandString"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Set the icon of the shop item at `uber_identifier` to `icon` */
            SetShopItemIcon: {
                icon: components["schemas"]["Icon"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Set the shop item at `uber_identifier` to be `hidden` */
            SetShopItemHidden: {
                hidden: components["schemas"]["CommandBoolean"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Set the shop item at `uber_identifier` to be `locked` */
            SetShopItemLocked: {
                locked: components["schemas"]["CommandBoolean"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Set the display name of the wheel item in `wheel` at `position` to `name` */
            SetWheelItemName: {
                name: components["schemas"]["CommandString"];
                position: components["schemas"]["WheelItemPosition"];
                wheel: number;
            };
        } | {
            /** @description Set the description of the wheel item in `wheel` at `position` to `description` */
            SetWheelItemDescription: {
                description: components["schemas"]["CommandString"];
                position: components["schemas"]["WheelItemPosition"];
                wheel: number;
            };
        } | {
            /** @description Set the icon of the wheel item in `wheel` at `position` to `icon` */
            SetWheelItemIcon: {
                icon: components["schemas"]["Icon"];
                position: components["schemas"]["WheelItemPosition"];
                wheel: number;
            };
        } | {
            /** @description Set the rgba color of the wheel item in `wheel` at `position` to `red`, `green`, `blue`, `alpha` */
            SetWheelItemColor: {
                alpha: components["schemas"]["CommandInteger"];
                blue: components["schemas"]["CommandInteger"];
                green: components["schemas"]["CommandInteger"];
                position: components["schemas"]["WheelItemPosition"];
                red: components["schemas"]["CommandInteger"];
                wheel: number;
            };
        } | {
            /** @description When pressing `bind` with the wheel item in `wheel` at `position` selected, lookup and perform `action` */
            SetWheelItemAction: {
                action: number;
                bind: components["schemas"]["WheelBind"];
                position: components["schemas"]["WheelItemPosition"];
                wheel: number;
            };
        } | {
            /** @description Remove the wheel item in `wheel` at `position` */
            DestroyWheelItem: {
                position: components["schemas"]["WheelItemPosition"];
                wheel: number;
            };
        } | {
            /** @description Switch the active wheel to `wheel` */
            SwitchWheel: {
                wheel: number;
            };
        } | {
            /** @description If a `wheel` is `pinned`, it should remain the active wheel after closing and reopening the randomizer wheel */
            SetWheelPinned: {
                pinned: components["schemas"]["CommandBoolean"];
                wheel: number;
            };
        } | {
            /** @description Reset all wheel items to their default state */
            ResetAllWheels: Record<string, never>;
        } | {
            /** @description Sets the hint text for the trial using `uber_identifier` to `text` */
            SetTrialHint: {
                text: components["schemas"]["CommandString"];
                uber_identifier: components["schemas"]["UberIdentifier"];
            };
        } | {
            /** @description Closes any open menu screen */
            CloseMenu: Record<string, never>;
        } | {
            /** @description Closes the weapon wheel */
            CloseWeaponWheel: Record<string, never>;
        } | {
            /** @description Write `message` into the client log */
            DebugLog: {
                message: components["schemas"]["CommandString"];
            };
        } | {
            DealEnemyDamage: {
                amount: components["schemas"]["CommandFloat"];
            };
        } | {
            ForceDealEnemyDamage: {
                amount: components["schemas"]["CommandFloat"];
            };
        };
        /** @description Command which returns [`Zone`] */
        CommandZone: {
            /** @description Return `value` */
            Constant: {
                value: components["schemas"]["Zone"];
            };
        } | {
            /** @description Execute `commands`, then use `last` for the return value */
            Multi: {
                commands: components["schemas"]["CommandVoid"][];
                last: components["schemas"]["CommandZone"];
            };
        } | {
            /** @description Return the zone Ori is currently in */
            CurrentZone: Record<string, never>;
        } | {
            /** @description Return the zone currently selected in the map */
            CurrentMapZone: Record<string, never>;
        };
        /**
         * @description Comparison Operations performed on numbers
         * @enum {integer}
         */
        Comparator: 0 | 1 | 2 | 3 | 4 | 5;
        ConfigValue: {
            default: boolean;
            /** @enum {string} */
            type: "Boolean";
        } | {
            /** Format: int32 */
            default: number;
            /** @enum {string} */
            type: "Integer";
        } | {
            /** Format: int32 */
            default: number;
            /** Format: int32 */
            max: number;
            /** Format: int32 */
            min: number;
            /** @enum {string} */
            type: "IntegerRange";
        } | {
            /** Format: float */
            default: number;
            /** @enum {string} */
            type: "Float";
        } | {
            /** Format: float */
            default: number;
            /** Format: float */
            max: number;
            /** Format: float */
            min: number;
            /** @enum {string} */
            type: "FloatRange";
        };
        Connection: {
            /** @description Whether this connection was implicitly generated by seedgen, e.g. entrance connections */
            implicitly_generated: boolean;
            requirement: components["schemas"]["Requirement"];
            to: number;
        };
        /**
         * @description Coordinate system of message boxes
         * @enum {integer}
         */
        CoordinateSystem: 0 | 1 | 2;
        /**
         * @description The logical difficulty to expect in a seed
         *
         *     This represents how demanding the required core movement should be
         *     Difficulties don't include glitches by default, these are handled separately with [`Trick`]s
         *
         *     See the [Paths wiki page](https://wiki.orirando.com/seedgen/paths) for more information
         * @enum {string}
         */
        Difficulty: "Moki" | "Gorlek" | "Kii" | "Unsafe";
        DifficultyInfo: {
            description: string;
            name: components["schemas"]["Difficulty"];
        };
        Entrance: {
            id: components["schemas"]["i32"];
            requirement: components["schemas"]["Requirement"];
            target: string;
        };
        /**
         * @description Available slots for [`Equipment`] (the stuff displayed at the bottom between your energy and health)
         * @enum {integer}
         */
        EquipSlot: 0 | 1 | 2;
        /**
         * @description Abilities which have to be equipped before use
         * @enum {integer}
         */
        Equipment: 1000 | 1001 | 1002 | 1003 | 1004 | 1005 | 2000 | 2001 | 2002 | 2003 | 2004 | 2005 | 2006 | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 | 2016 | 2017 | 2018 | 2019 | 3000 | 3001 | 3002 | 3003 | 3004 | 3005 | 4000 | 4001 | 4002 | 4003 | 4004 | 4005 | 4006 | 4007 | 4008 | 4009;
        /**
         * @description Generic icons
         * @enum {integer}
         */
        GenericIcon: 0;
        Graph: {
            default_entrance_connections: components["schemas"]["HashMap_i32_i32"];
            extern_requirements: components["schemas"]["Requirement"][];
            nodes: components["schemas"]["Node"][];
        };
        GreaterOneU8: number;
        /**
         * @description Icons used in the Grom shop
         * @enum {integer}
         */
        GromIcon: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        HashMap_String_ConfigArg: {
            [key: string]: {
                description?: string | null;
                name: string;
                value: components["schemas"]["ConfigValue"];
            };
        };
        HashMap_String_HashMap_String_String: {
            [key: string]: {
                [key: string]: string;
            };
        };
        HashMap_String_SnippetInfo: {
            [key: string]: {
                /** @description Metadata about the snippet */
                metadata: components["schemas"]["Metadata"];
                /** @description Where this snippet came from */
                origin: components["schemas"]["AssetOrigin"];
                /** @description Whether this snippet or anything in its include tree requires local files */
                treeRequiresLocalFiles: boolean;
            };
        };
        HashMap_String_Source: {
            [key: string]: {
                /**
                 * @description The contents of the file, which will be referenced for better error messages.
                 *
                 *     This should be the same contents you were parsing, otherwise error messages will reference arbitrary spans in your source and possibly panic.
                 */
                content: string;
                /**
                 * @description An identifier to be used in error messages that should allow the reader to determine which file the error originated from.
                 *
                 *     This might be the file path relative to the workspace root, or just the filename.
                 */
                id: string;
            };
        };
        HashMap_String_UniversePresetInfo: {
            [key: string]: {
                /** @description The universe preset */
                content: components["schemas"]["UniversePreset"];
                /** @description Where this universe preset came from */
                origin: components["schemas"]["AssetOrigin"];
            };
        };
        HashMap_String_WorldPresetInfo: {
            [key: string]: {
                /** @description The world preset */
                content: components["schemas"]["WorldPreset"];
                /** @description Where this world preset came from */
                origin: components["schemas"]["AssetOrigin"];
            };
        };
        HashMap_i32_i32: {
            [key: string]: number;
        };
        HashSet_String: string[];
        HashSet_Trick: ("SwordSentryJump" | "HammerSentryJump" | "ShurikenBreak" | "SentryBreak" | "HammerBreak" | "SpearBreak" | "SentryBurn" | "RemoveKillPlane" | "LaunchSwap" | "SentrySwap" | "FlashSwap" | "BlazeSwap" | "WaveDash" | "GrenadeJump" | "SwordJump" | "AerialHammerJump" | "GlideJump" | "GlideHammerJump" | "CoyoteHammerJump" | "WallHammerJump" | "GroundedHammerJump" | "HammerExtension" | "GrenadeRedirect" | "SentryRedirect" | "PauseFloat" | "SpearJump" | "GlideBashChain" | "DoubleJumpBashChain" | "DashBashChain" | "LaunchBashChain" | "Unpopular")[];
        /**
         * @description Horizontal anchor of message boxes
         *
         *     Note that message boxes are bigger than their visual background, so this can produce unexpected results
         * @enum {integer}
         */
        HorizontalAnchor: 0 | 1 | 2;
        /** @description Icons which can be used in shops or wheels */
        Icon: {
            Generic: components["schemas"]["GenericIcon"];
        } | {
            Shard: components["schemas"]["Shard"];
        } | {
            Equipment: components["schemas"]["Equipment"];
        } | {
            Opher: components["schemas"]["OpherIcon"];
        } | {
            Lupo: components["schemas"]["LupoIcon"];
        } | {
            Grom: components["schemas"]["GromIcon"];
        } | {
            Tuley: components["schemas"]["TuleyIcon"];
        } | {
            File: string;
        } | {
            Bundle: string;
        };
        /** @description Information about a pickup location */
        LocDataEntry: {
            /** @description Unique identifier for this pickup location which is used in `paths.wotwl` */
            identifier: string;
            /** @description Vanilla map icon */
            map_icon: components["schemas"]["MapIcon"];
            map_position?: null | components["schemas"]["Position"];
            position?: null | components["schemas"]["Position"];
            /**
             * @description `UberIdentifier` where this pickup location's corresponding world state is stored
             *
             *     pickup locations are either stored as booleans or as integers where being above a certain value means the pickup is collected
             */
            uber_identifier: components["schemas"]["UberIdentifier"];
            /**
             * Format: int32
             * @description `None` if `uber_identifier` holds a boolean value. Otherwise, has the minimum integer value at which this pickup is collected
             */
            value?: number | null;
            /** @description Map zone containing this pickup location */
            zone: components["schemas"]["Zone"];
        };
        /**
         * @default INFO
         * @enum {string}
         */
        LogLevelFilter: "OFF" | "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE";
        /**
         * @description Icons used in the Lupo shop
         * @enum {integer}
         */
        LupoIcon: 0 | 1 | 2;
        /**
         * @description Icons used in the map
         * @enum {integer}
         */
        MapIcon: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 40 | 41 | 42 | 43 | 44 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 100 | 101 | 102 | 103 | 104 | 105 | 106 | 107 | 108 | 109 | 110 | 111 | 112 | 113 | 114 | 115 | 116 | 117;
        MapIconCondition: {
            comparator: components["schemas"]["Comparator"];
            uberIdentifier: components["schemas"]["UberIdentifier"];
            /** Format: float */
            value: number;
        };
        MapIconInfo: {
            icon: components["schemas"]["MapIcon"];
            label: string;
            positions: components["schemas"]["Position"][];
            visibleIfAny: components["schemas"]["MapIconCondition"][];
        };
        MapIcons: {
            /**
             * Format: int64
             * @description Hash of `map_icons`
             */
            hash: number;
            /** @description List of logically relevant map icons */
            mapIcons: components["schemas"]["MapIconInfo"][];
        };
        /** @description Metadata about a snippet */
        Metadata: {
            /** @description Category shared with other snippets */
            category?: string | null;
            /** @default {} */
            config: components["schemas"]["HashMap_String_ConfigArg"];
            /** @description Longer description */
            description?: string | null;
            /** @description Whether the snippet should be hidden from the options when generating seeds */
            hidden: boolean;
            /** @description Included snippets */
            includes: string[];
            /** @description Display name */
            name?: string | null;
            /**
             * @description Whether this snippet requires local files, preventing it from being inlined
             *
             *     Note that included snippets may require local files even if this one doesn't
             */
            requiresLocalFiles: boolean;
        };
        Node: {
            Anchor: components["schemas"]["Anchor"];
        } | {
            Pickup: components["schemas"]["LocDataEntry"];
        } | {
            State: components["schemas"]["StateDataEntry"];
        } | {
            LogicalState: string;
        };
        /** @description Select data from a [`LocDataEntry`] */
        NodeSummary: {
            /** @description The identifier */
            identifier: string;
            position?: null | components["schemas"]["Position"];
            /** @description The [`Zone`] */
            zone: components["schemas"]["Zone"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandBoolean_EqualityComparator: {
            left: components["schemas"]["CommandBoolean"];
            /**
             * @description Comparison Operations performed on strings or booleans
             * @enum {integer}
             */
            operator: 0 | 1;
            right: components["schemas"]["CommandBoolean"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandBoolean_LogicOperator: {
            left: components["schemas"]["CommandBoolean"];
            /**
             * @description Logic Operations performed on booleans
             * @enum {integer}
             */
            operator: 0 | 1;
            right: components["schemas"]["CommandBoolean"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandFloat_ArithmeticOperator: {
            left: components["schemas"]["CommandFloat"];
            /**
             * @description Arithmetic Operations performed on numbers
             * @enum {integer}
             */
            operator: 0 | 1 | 2 | 3;
            right: components["schemas"]["CommandFloat"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandFloat_Comparator: {
            left: components["schemas"]["CommandFloat"];
            /**
             * @description Comparison Operations performed on numbers
             * @enum {integer}
             */
            operator: 0 | 1 | 2 | 3 | 4 | 5;
            right: components["schemas"]["CommandFloat"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandInteger_ArithmeticOperator: {
            left: components["schemas"]["CommandInteger"];
            /**
             * @description Arithmetic Operations performed on numbers
             * @enum {integer}
             */
            operator: 0 | 1 | 2 | 3;
            right: components["schemas"]["CommandInteger"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandInteger_Comparator: {
            left: components["schemas"]["CommandInteger"];
            /**
             * @description Comparison Operations performed on numbers
             * @enum {integer}
             */
            operator: 0 | 1 | 2 | 3 | 4 | 5;
            right: components["schemas"]["CommandInteger"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandString_Concatenator: {
            left: components["schemas"]["CommandString"];
            /**
             * @description Concatenation performed on strings
             * @enum {integer}
             */
            operator: 0;
            right: components["schemas"]["CommandString"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandString_EqualityComparator: {
            left: components["schemas"]["CommandString"];
            /**
             * @description Comparison Operations performed on strings or booleans
             * @enum {integer}
             */
            operator: 0 | 1;
            right: components["schemas"]["CommandString"];
        };
        /** @description An Operation performed on two values */
        Operation_CommandZone_EqualityComparator: {
            left: components["schemas"]["CommandZone"];
            /**
             * @description Comparison Operations performed on strings or booleans
             * @enum {integer}
             */
            operator: 0 | 1;
            right: components["schemas"]["CommandZone"];
        };
        /**
         * @description Icons used in the Opher shop
         * @enum {integer}
         */
        OpherIcon: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
        /** @description `x`/`y` position */
        Position: {
            /** Format: float */
            x: number;
            /** Format: float */
            y: number;
        };
        /**
         * @description Special groups to display a preset in
         * @enum {string}
         */
        PresetGroup: "Base";
        /** @description Information for the user about a [`UniversePreset`] or [`WorldPreset`] */
        PresetInfo: {
            /** @description Extended description */
            description?: string | null;
            group?: null | components["schemas"]["PresetGroup"];
            /** @description Display name */
            name?: string | null;
        };
        ReachCheck: {
            /**
             * Format: int64
             * @description Current hash of logically relevant map icons
             */
            map_icons_hash: number;
            /** @description List of indices into logically reachable map icons */
            reachable: number[];
            /**
             * Format: int64
             * @description Current hash of logically relevant UberStates
             */
            relevant_uber_states_hash: number;
        };
        ReachCheckBody: {
            /** @description seedgen_info.json contents from within the seed */
            seedgen_info: string;
            /** @description Current values of logically relevant UberStates */
            uber_states: [
                [
                    number,
                    number
                ],
                number
            ][];
        };
        Refill: {
            requirement: components["schemas"]["Requirement"];
            value: components["schemas"]["RefillValue"];
        };
        RefillValue: "Full" | "Checkpoint" | {
            /** Format: float */
            Health: number;
        } | {
            /** Format: float */
            Energy: number;
        };
        RelevantUberStates: {
            /**
             * Format: int64
             * @description Hash of `identifiers`
             */
            hash: number;
            /** @description List of logically relevant UberStates */
            identifiers: components["schemas"]["UberIdentifier"][];
        };
        Requirement: "Free" | "Impossible" | "NormalGameDifficulty" | {
            Difficulty: components["schemas"]["Difficulty"];
        } | {
            Trick: components["schemas"]["Trick"];
        } | {
            State: number;
        } | "Water" | {
            Skill: components["schemas"]["Skill"];
        } | {
            Shard: components["schemas"]["Shard"];
        } | {
            Teleporter: components["schemas"]["Teleporter"];
        } | {
            SpiritLight: number;
        } | {
            GorlekOre: number;
        } | {
            Keystone: number;
        } | {
            /** Format: float */
            Danger: number;
        } | {
            /** Format: float */
            Damage: number;
        } | {
            NonConsumingEnergySkill: components["schemas"]["Skill"];
        } | {
            EnergySkill: Record<string, never>[];
        } | {
            /** Format: float */
            ShurikenBreak: number;
        } | {
            /** Format: float */
            SentryBreak: number;
        } | {
            Extern: number;
        } | {
            /** Format: float */
            BreakWall: number;
        } | {
            /** Format: float */
            Boss: number;
        } | {
            Combat: [
                "Mantis" | "Slug" | "WeakSlug" | "BombSlug" | "CorruptSlug" | "SneezeSlug" | "ShieldSlug" | "Lizard" | "Bat" | "Hornbug" | "Skeeto" | "SmallSkeeto" | "Bee" | "Nest" | "Crab" | "SpinCrab" | "Tentacle" | "Balloon" | "Miner" | "MaceMiner" | "ShieldMiner" | "CrystalMiner" | "ShieldCrystalMiner" | "Sandworm" | "Spiderling" | "EnergyRefill",
                number
            ][];
        } | {
            And: components["schemas"]["Requirement"][];
        } | {
            Or: components["schemas"]["Requirement"][];
        };
        /** @description Complete data to create a logic spoiler for the seed */
        SeedSpoiler: {
            /**
             * @description For each world, all the entrance connections
             *
             *     If a world's list of entrance connections is empty, the entrances were not randomized
             */
            entrances: [
                string,
                string
            ][][];
            /** @description Each [`SpoilerGroup`] represents one "step" of placements */
            groups: components["schemas"]["SpoilerGroup"][];
            /** @description An ordered list describing the preplaced items */
            preplacements: components["schemas"]["SpoilerPlacement"][];
            /** @description Anchor identifier of all the spawn locations */
            spawns: string[];
        };
        /**
         * @description Spirit Shards
         * @enum {integer}
         */
        Shard: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47;
        /**
         * @description Skills, sometimes also called Abilities
         *
         *     Currently excludes unused skills
         * @enum {integer}
         */
        Skill: 0 | 3 | 5 | 8 | 14 | 15 | 23 | 51 | 57 | 62 | 74 | 77 | 97 | 98 | 100 | 101 | 102 | 104 | 106 | 108 | 109 | 115 | 116 | 118 | 119 | 120 | 121;
        /** @description Information about a snippet */
        SnippetInfo: {
            /** @description Metadata about the snippet */
            metadata: components["schemas"]["Metadata"];
            /** @description Where this snippet came from */
            origin: components["schemas"]["AssetOrigin"];
            /** @description Whether this snippet or anything in its include tree requires local files */
            treeRequiresLocalFiles: boolean;
        };
        /** @description Representation of a source file with the necessary information to display useful error messages. */
        Source: {
            /**
             * @description The contents of the file, which will be referenced for better error messages.
             *
             *     This should be the same contents you were parsing, otherwise error messages will reference arbitrary spans in your source and possibly panic.
             */
            content: string;
            /**
             * @description An identifier to be used in error messages that should allow the reader to determine which file the error originated from.
             *
             *     This might be the file path relative to the workspace root, or just the filename.
             */
            id: string;
        };
        /** @description The Spawn location, which may either be fixed or randomly decided during seed generation */
        Spawn: {
            /** @description Spawn in a specific location, described by the anchor name from the logic file */
            Set: string;
        } | "Random" | "FullyRandom";
        SpawnAnchors: {
            /** @description List of spawnable anchor identifiers */
            identifiers: string[];
            /** @description Indices into `identifiers` for viable moki random teleporter spawns */
            mokiTeleporters: number[];
            /** @description Indices into `identifiers` for viable random teleporter spawns above moki */
            teleporters: number[];
        };
        /** @description One "step" of placements in a [`SeedSpoiler`] */
        SpoilerGroup: {
            /** @description The set of items that were placed as forced progression, if any */
            forcedItems: components["schemas"]["SpoilerItem"][];
            /** @description An ordered list describing the placed items */
            placements: components["schemas"]["SpoilerPlacement"][];
            /** @description The new reachables for each world */
            reachable: components["schemas"]["NodeSummary"][][];
        };
        SpoilerItem: {
            /** @description The placed command */
            command: components["schemas"]["CommandVoid"];
            /** @description The readable name of the placed item, which usually varies from the `command`s [`Display`] implementation */
            name: string;
        };
        /** @description One item placed on one location */
        SpoilerPlacement: {
            /** @description The placed item */
            item: components["schemas"]["SpoilerItem"];
            /** @description The placement location */
            location: components["schemas"]["NodeSummary"];
            /** @description The "sending" world */
            originWorldIndex: number;
            /** @description The "receiving" world */
            targetWorldIndex: number;
        };
        /** @description Information about an obtainable world state */
        StateDataEntry: {
            /** @description Unique identifier for this world state which is used in `paths.wotwl` */
            identifier: string;
            /**
             * @description `UberIdentifier` where this world state is stored
             *
             *     world states are either stored as booleans or as integers where being above a certain value means the world state is completed
             */
            uber_identifier: components["schemas"]["UberIdentifier"];
            /**
             * Format: int32
             * @description `None` if `uber_identifier` holds a boolean value. Otherwise, has the minimum integer value at which this world state is completed
             */
            value?: number | null;
        };
        StringOrPlaceholder: {
            Value: string;
        } | {
            ZoneOfPlaceholder: components["schemas"]["CommandVoid"];
        } | {
            ItemOnPlaceholder: components["schemas"]["Trigger"];
        } | {
            CountInZonePlaceholder: Record<string, never>[];
        };
        /**
         * @description Spirit Wells which exist in the base game
         * @enum {integer}
         */
        Teleporter: 16 | 1 | 5 | 17 | 3 | 0 | 7 | 8 | 4 | 6 | 2 | 13 | 9 | 10 | 11 | 14 | 12 | 15;
        /**
         * @description A Trick that can be logically required
         *
         *     This includes mostly Glitches but also other techniques that can be toggled for logic, such as damage boosting
         *
         *     See the [Paths wiki page](https://wiki.orirando.com/seedgen/paths) for more information
         * @enum {string}
         */
        Trick: "SwordSentryJump" | "HammerSentryJump" | "ShurikenBreak" | "SentryBreak" | "HammerBreak" | "SpearBreak" | "SentryBurn" | "RemoveKillPlane" | "LaunchSwap" | "SentrySwap" | "FlashSwap" | "BlazeSwap" | "WaveDash" | "GrenadeJump" | "SwordJump" | "AerialHammerJump" | "GlideJump" | "GlideHammerJump" | "CoyoteHammerJump" | "WallHammerJump" | "GroundedHammerJump" | "HammerExtension" | "GrenadeRedirect" | "SentryRedirect" | "PauseFloat" | "SpearJump" | "GlideBashChain" | "DoubleJumpBashChain" | "DashBashChain" | "LaunchBashChain" | "Unpopular";
        TrickInfo: {
            description: string;
            min_difficulty: components["schemas"]["Difficulty"];
            name: components["schemas"]["Trick"];
        };
        Tricks: "All" | {
            Some: components["schemas"]["HashSet_Trick"];
        };
        /** @description Trigger for an [`Event`] */
        Trigger: {
            /** @description Specific client events */
            ClientEvent: components["schemas"]["ClientEvent"];
        } | {
            /** @description Trigger on every change to an UberIdentifier */
            Binding: components["schemas"]["UberIdentifier"];
        } | {
            /** @description Trigger when the condition changes from `false` to `true` */
            Condition: components["schemas"]["TriggerCondition"];
        };
        TriggerCondition: {
            condition: components["schemas"]["CommandBoolean"];
            id?: number | null;
        };
        /**
         * @description Icons used in the Tuley shop
         * @enum {integer}
         */
        TuleyIcon: 0 | 1 | 2 | 3 | 4 | 5;
        UberIdentifier: [
            number,
            number
        ];
        /**
         * @description A collection of settings that can be applied to existing settings
         *
         *     Use [`UniversePreset::apply`] to merge a `UniversePreset` into existing [`UniverseSettings`]
         *
         *     # Examples
         *
         *     ```
         *     # use wotw_seedgen_data::assets::UniversePreset;
         *     use wotw_seedgen_data::{assets::{NoAccess, UniversePresetSettings, WorldPresetSettings}, Spawn, UniverseSettings};
         *
         *     let mut universe_settings = UniverseSettings::new("seed".to_string());
         *
         *     let preset = UniversePreset {
         *         assets_version: 1,
         *         info: None,
         *         settings: UniversePresetSettings {
         *             world_settings: Some(vec![
         *                 WorldPresetSettings {
         *                     spawn: Some(Spawn::Random),
         *                     ..Default::default()
         *                 }
         *             ]),
         *             ..Default::default()
         *         }
         *     };
         *
         *     preset.apply(&mut universe_settings, &NoAccess);
         *     assert_eq!(universe_settings.world_settings[0].spawn, Spawn::Random);
         *     ```
         *
         *     [`UniverseSettings`]: wotw_seedgen_settings::UniverseSettings
         */
        UniversePreset: components["schemas"]["UniversePresetSettings"] & {
            /**
             * Format: int32
             * @description Assets version this preset is compatible with
             */
            assetsVersion?: number;
            info?: null | components["schemas"]["PresetInfo"];
        };
        UniversePresetApplyBody: components["schemas"]["UniversePresetApplyBodySettings"] & {
            /** @description Presets to apply */
            presets: components["schemas"]["UniversePreset"][];
        };
        UniversePresetApplyBodySettings: components["schemas"]["UniversePresetApplyBodySettingsFull"] | components["schemas"]["UniversePresetApplyBodySettingsSeed"];
        UniversePresetApplyBodySettingsFull: {
            settings: components["schemas"]["UniverseSettings"];
        };
        UniversePresetApplyBodySettingsSeed: {
            seed: string;
        };
        /** @description Information about a universe preset */
        UniversePresetInfo: {
            /** @description The universe preset */
            content: components["schemas"]["UniversePreset"];
            /** @description Where this universe preset came from */
            origin: components["schemas"]["AssetOrigin"];
        };
        /**
         * @description Settings to apply to [`UniverseSettings`]
         *
         *     Mostly used inside a [`UniversePreset`] which offers compability features
         */
        UniversePresetSettings: {
            includes?: null | components["schemas"]["HashSet_String"];
            /** @description The seed that determines all randomness */
            seed?: string | null;
            /** @description The individual settings for each world of the seed */
            worldSettings?: components["schemas"]["WorldPresetSettings"][] | null;
        };
        /**
         * @description A representation of all the relevant settings when generating a seed
         *
         *     Using the same settings will result in generating the same seed (as long as the same seedgen version and snippets are used)
         *
         *     # Examples
         *
         *     ```
         *     # use wotw_seedgen_data::UniverseSettings;
         *     use wotw_seedgen_data::WorldSettings;
         *
         *     let universe_settings = UniverseSettings::new("seed".to_string());
         *
         *     assert_eq!(universe_settings.world_count(), 1);
         *     assert_eq!(universe_settings.world_settings[0], WorldSettings::default());
         *     assert_eq!(universe_settings.seed, "seed");
         *     ```
         */
        UniverseSettings: {
            /** @default {} */
            inlineSnippets: components["schemas"]["HashMap_String_Source"];
            /** @description The seed that determines all randomness */
            seed: string;
            /**
             * @description The individual settings for each world of the seed
             *
             *     This should never be empty
             */
            worldSettings: components["schemas"]["WorldSettings"][];
        };
        /**
         * @description Vertical anchor of message boxes
         * @enum {integer}
         */
        VerticalAnchor: 0 | 1 | 2;
        /**
         * @description Possible input configurations for an item in a weapon wheel like menu
         * @enum {integer}
         */
        WheelBind: 0 | 1 | 2;
        /**
         * @description Positioning in a weapon wheel like menu
         * @enum {integer}
         */
        WheelItemPosition: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
        /**
         * @description A collection of settings that can be applied to one world of existing settings
         *
         *     Use [`WorldPreset::apply`] to merge a `WorldPreset` into existing [`WorldSettings`]
         *
         *     # Examples
         *
         *     ```
         *     # use wotw_seedgen_data::assets::WorldPreset;
         *     use wotw_seedgen_data::{assets::{NoAccess, WorldPresetSettings}, Spawn, WorldSettings};
         *
         *     let mut world_settings = WorldSettings::default();
         *
         *     let world_preset = WorldPreset {
         *         assets_version: 1,
         *         info: None,
         *         settings: WorldPresetSettings {
         *             spawn: Some(Spawn::Random),
         *             ..Default::default()
         *         }
         *     };
         *
         *     world_preset.apply(&mut world_settings, &NoAccess);
         *     assert_eq!(world_settings.spawn, Spawn::Random);
         *     ```
         *
         *     [`WorldSettings`]: wotw_seedgen_settings::WorldSettings
         */
        WorldPreset: components["schemas"]["WorldPresetSettings"] & {
            /**
             * Format: int32
             * @description Assets version this preset is compatible with
             */
            assetsVersion?: number;
            info?: null | components["schemas"]["PresetInfo"];
        };
        WorldPresetApplyBody: {
            /** @description Presets to apply */
            presets: components["schemas"]["WorldPreset"][];
            settings?: null | components["schemas"]["WorldSettings"];
        };
        /** @description Information about a world preset */
        WorldPresetInfo: {
            /** @description The world preset */
            content: components["schemas"]["WorldPreset"];
            /** @description Where this world preset came from */
            origin: components["schemas"]["AssetOrigin"];
        };
        /**
         * @description Settings to apply to [`WorldSettings`]
         *
         *     Mostly used inside a [`WorldPreset`] which offers compability features
         */
        WorldPresetSettings: {
            difficulty?: null | components["schemas"]["Difficulty"];
            /** @description Logically assume hard in-game difficulty */
            hard?: boolean | null;
            includes?: null | components["schemas"]["HashSet_String"];
            /** @description Randomize settings before applying further changes */
            randomSettings?: boolean | null;
            randomizeEntrances?: null | components["schemas"]["GreaterOneU8"];
            snippetConfig?: null | components["schemas"]["HashMap_String_HashMap_String_String"];
            /** @description Names of snippets to use */
            snippets?: string[] | null;
            spawn?: null | components["schemas"]["Spawn"];
            tricks?: null | components["schemas"]["Tricks"];
        };
        /**
         * @description Seed settings bound to a specific world of a seed
         *
         *     See the [Multiplayer wiki page](https://wiki.orirando.com/features/multiplayer) for an explanation of worlds
         * @default {
         *       "difficulty": "Moki",
         *       "hard": false,
         *       "randomizeEntrances": null,
         *       "snippetConfig": {},
         *       "snippets": [],
         *       "spawn": {
         *         "Set": "MarshSpawn.Main"
         *       },
         *       "tricks": []
         *     }
         */
        WorldSettings: {
            /** @default Moki */
            difficulty: components["schemas"]["Difficulty"];
            /**
             * @description Logically assume hard in-game difficulty
             * @default false
             */
            hard: boolean;
            /** @default null */
            randomizeEntrances: null | components["schemas"]["GreaterOneU8"];
            /** @default {} */
            snippetConfig: components["schemas"]["HashMap_String_HashMap_String_String"];
            /**
             * @description Names of snippets to use
             * @default []
             */
            snippets: string[];
            /**
             * @default {
             *       "Set": "MarshSpawn.Main"
             *     }
             */
            spawn: components["schemas"]["Spawn"];
            /** @default [] */
            tricks: components["schemas"]["HashSet_Trick"];
        };
        /**
         * @description World zones as indicated on the map
         * @enum {integer}
         */
        Zone: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14;
        /** Format: int32 */
        i32: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Alignment = components['schemas']['Alignment'];
export type Anchor = components['schemas']['Anchor'];
export type AssetOrigin = components['schemas']['AssetOrigin'];
export type ClientEvent = components['schemas']['ClientEvent'];
export type CommandBoolean = components['schemas']['CommandBoolean'];
export type CommandFloat = components['schemas']['CommandFloat'];
export type CommandInteger = components['schemas']['CommandInteger'];
export type CommandString = components['schemas']['CommandString'];
export type CommandVoid = components['schemas']['CommandVoid'];
export type CommandZone = components['schemas']['CommandZone'];
export type Comparator = components['schemas']['Comparator'];
export type ConfigValue = components['schemas']['ConfigValue'];
export type Connection = components['schemas']['Connection'];
export type CoordinateSystem = components['schemas']['CoordinateSystem'];
export type Difficulty = components['schemas']['Difficulty'];
export type DifficultyInfo = components['schemas']['DifficultyInfo'];
export type Entrance = components['schemas']['Entrance'];
export type EquipSlot = components['schemas']['EquipSlot'];
export type Equipment = components['schemas']['Equipment'];
export type GenericIcon = components['schemas']['GenericIcon'];
export type Graph = components['schemas']['Graph'];
export type GreaterOneU8 = components['schemas']['GreaterOneU8'];
export type GromIcon = components['schemas']['GromIcon'];
export type HashMapStringConfigArg = components['schemas']['HashMap_String_ConfigArg'];
export type HashMapStringHashMapStringString = components['schemas']['HashMap_String_HashMap_String_String'];
export type HashMapStringSnippetInfo = components['schemas']['HashMap_String_SnippetInfo'];
export type HashMapStringSource = components['schemas']['HashMap_String_Source'];
export type HashMapStringUniversePresetInfo = components['schemas']['HashMap_String_UniversePresetInfo'];
export type HashMapStringWorldPresetInfo = components['schemas']['HashMap_String_WorldPresetInfo'];
export type HashMapI32I32 = components['schemas']['HashMap_i32_i32'];
export type HashSetString = components['schemas']['HashSet_String'];
export type HashSetTrick = components['schemas']['HashSet_Trick'];
export type HorizontalAnchor = components['schemas']['HorizontalAnchor'];
export type Icon = components['schemas']['Icon'];
export type LocDataEntry = components['schemas']['LocDataEntry'];
export type LogLevelFilter = components['schemas']['LogLevelFilter'];
export type LupoIcon = components['schemas']['LupoIcon'];
export type MapIcon = components['schemas']['MapIcon'];
export type MapIconCondition = components['schemas']['MapIconCondition'];
export type MapIconInfo = components['schemas']['MapIconInfo'];
export type MapIcons = components['schemas']['MapIcons'];
export type Metadata = components['schemas']['Metadata'];
export type Node = components['schemas']['Node'];
export type NodeSummary = components['schemas']['NodeSummary'];
export type OperationCommandBooleanEqualityComparator = components['schemas']['Operation_CommandBoolean_EqualityComparator'];
export type OperationCommandBooleanLogicOperator = components['schemas']['Operation_CommandBoolean_LogicOperator'];
export type OperationCommandFloatArithmeticOperator = components['schemas']['Operation_CommandFloat_ArithmeticOperator'];
export type OperationCommandFloatComparator = components['schemas']['Operation_CommandFloat_Comparator'];
export type OperationCommandIntegerArithmeticOperator = components['schemas']['Operation_CommandInteger_ArithmeticOperator'];
export type OperationCommandIntegerComparator = components['schemas']['Operation_CommandInteger_Comparator'];
export type OperationCommandStringConcatenator = components['schemas']['Operation_CommandString_Concatenator'];
export type OperationCommandStringEqualityComparator = components['schemas']['Operation_CommandString_EqualityComparator'];
export type OperationCommandZoneEqualityComparator = components['schemas']['Operation_CommandZone_EqualityComparator'];
export type OpherIcon = components['schemas']['OpherIcon'];
export type Position = components['schemas']['Position'];
export type PresetGroup = components['schemas']['PresetGroup'];
export type PresetInfo = components['schemas']['PresetInfo'];
export type ReachCheck = components['schemas']['ReachCheck'];
export type ReachCheckBody = components['schemas']['ReachCheckBody'];
export type Refill = components['schemas']['Refill'];
export type RefillValue = components['schemas']['RefillValue'];
export type RelevantUberStates = components['schemas']['RelevantUberStates'];
export type Requirement = components['schemas']['Requirement'];
export type SeedSpoiler = components['schemas']['SeedSpoiler'];
export type Shard = components['schemas']['Shard'];
export type Skill = components['schemas']['Skill'];
export type SnippetInfo = components['schemas']['SnippetInfo'];
export type Source = components['schemas']['Source'];
export type Spawn = components['schemas']['Spawn'];
export type SpawnAnchors = components['schemas']['SpawnAnchors'];
export type SpoilerGroup = components['schemas']['SpoilerGroup'];
export type SpoilerItem = components['schemas']['SpoilerItem'];
export type SpoilerPlacement = components['schemas']['SpoilerPlacement'];
export type StateDataEntry = components['schemas']['StateDataEntry'];
export type StringOrPlaceholder = components['schemas']['StringOrPlaceholder'];
export type Teleporter = components['schemas']['Teleporter'];
export type Trick = components['schemas']['Trick'];
export type TrickInfo = components['schemas']['TrickInfo'];
export type Tricks = components['schemas']['Tricks'];
export type Trigger = components['schemas']['Trigger'];
export type TriggerCondition = components['schemas']['TriggerCondition'];
export type TuleyIcon = components['schemas']['TuleyIcon'];
export type UberIdentifier = components['schemas']['UberIdentifier'];
export type UniversePreset = components['schemas']['UniversePreset'];
export type UniversePresetApplyBody = components['schemas']['UniversePresetApplyBody'];
export type UniversePresetApplyBodySettings = components['schemas']['UniversePresetApplyBodySettings'];
export type UniversePresetApplyBodySettingsFull = components['schemas']['UniversePresetApplyBodySettingsFull'];
export type UniversePresetApplyBodySettingsSeed = components['schemas']['UniversePresetApplyBodySettingsSeed'];
export type UniversePresetInfo = components['schemas']['UniversePresetInfo'];
export type UniversePresetSettings = components['schemas']['UniversePresetSettings'];
export type UniverseSettings = components['schemas']['UniverseSettings'];
export type VerticalAnchor = components['schemas']['VerticalAnchor'];
export type WheelBind = components['schemas']['WheelBind'];
export type WheelItemPosition = components['schemas']['WheelItemPosition'];
export type WorldPreset = components['schemas']['WorldPreset'];
export type WorldPresetApplyBody = components['schemas']['WorldPresetApplyBody'];
export type WorldPresetInfo = components['schemas']['WorldPresetInfo'];
export type WorldPresetSettings = components['schemas']['WorldPresetSettings'];
export type WorldSettings = components['schemas']['WorldSettings'];
export type Zone = components['schemas']['Zone'];
export type I32 = components['schemas']['i32'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
