export type Settings = {
  ServerHost: string,
  ServerTLS: boolean,
  DeveloperMode: boolean,
  DebugControls: boolean,
  AlwaysShowKeystones: boolean,
  EnableWorldMap: boolean,
  GrappleMouseControl: boolean,
  BurrowMouseControl: boolean,
  WaterDashMouseControl: boolean,
  HybridMouseControl: boolean,
  LaunchWithTracker: boolean,
  FunnyMoney: boolean,
  InvertFastSwim: boolean,
  LockCursor: boolean,
  UpdateToPrereleaseVersions: boolean,
  ShowStatsAfterFinish: boolean,
  ShowAllSecrets: boolean,
  DisableAutoAim: boolean,
  EnableAutomaticCutsceneSkipping: boolean,
  EnableMinimap: boolean,
  EnableNativeControllerSupport: boolean,
  ShowTransparentOutOfLogicIcons: boolean,
  MapPanSpeed: number,
  CameraShakeIntensity: number,
  LocalTrackerWindowPositionX: number,
  LocalTrackerWindowPositionY: number,
  LocalTrackerWindowPositionWidth: number,
  LocalTrackerWindowPositionHeight: number,
  LocalTrackerShowTimer: boolean,
  LocalTrackerTransparent: boolean,
  LocalTrackerAlwaysOnTop: boolean,
  LocalTrackerIgnoreMouse: boolean,
  LocalTrackerShowWillowHearts: boolean,
  LocalTrackerHideHeartsUntilFirstHeart: boolean,
  GameLaunchMethod: "steam" | "microsoft-store" | "standalone",
  ModloaderMethod: "proxy" | "inject",
  ValidateProxyModloader: boolean,
  GameBinaryPath: string,
  SteamBinaryPath: string,
}

export type SettingKey = keyof Settings

export type Setting = {
  key: SettingKey,
  value: Settings[SettingKey],
}
