export type Settings = {
  ServerHost: string,
  ServerTLS: boolean,
  UseMicrosoftStore: boolean,
  DeveloperMode: boolean,
  DebugControls: boolean,
  HideQuestFilter: boolean,
  HideWarpFilter: boolean,
  HideCollectableFilter: boolean,
  AlwaysShowWarps: boolean,
  AlwaysShowKeystones: boolean,
  AlwaysShowKeystoneDoors: boolean,
  EnableWorldMap: boolean,
  GrappleMouseControl: boolean,
  BurrowMouseControl: boolean,
  WaterDashMouseControl: boolean,
  HybridMouseControl: boolean,
  LaunchWithTracker: boolean,
  FunnyMoney: boolean,
  InvertFastSwim: boolean,
  LockCursor: boolean,
  UpdateToPrereleaseVersions: boolean,
  ShowStatsAfterFinish: boolean,
  ShowAllSecrets: boolean,
  DisableAutoAim: boolean,
  SelectInLogicFilterByDefault: boolean,
  EnableMinimap: boolean,
  EnableNativeControllerSupport: boolean,
  MapIconTransparency: number,
  MapPanSpeed: number,
  CameraShakeIntensity: number,
  LocalTrackerWindowPositionX: number,
  LocalTrackerWindowPositionY: number,
  LocalTrackerWindowPositionWidth: number,
  LocalTrackerWindowPositionHeight: number,
  LocalTrackerShowTimer: boolean,
  LocalTrackerTransparent: boolean,
  LocalTrackerAlwaysOnTop: boolean,
  LocalTrackerIgnoreMouse: boolean,
  LocalTrackerShowWillowHearts: boolean,
  LocalTrackerHideHeartsUntilFirstHeart: boolean,
  GameOrSteamBinaryPath: string,
}

export type SettingKey = keyof Settings

export type Setting = {
  key: SettingKey,
  value: Settings[SettingKey],
}
